#!/usr/bin/env bash
#Bash script that configures an Ubuntu server

cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed '1s/^/8.8.8.8    facebook.com\n/' ~/hosts.new
cat ~/hosts.new > /etc/hosts
