#!/usr/bin/env bash
#Bash script that configures an Ubuntu server

FILE="/etc/hosts"
cp $FILE ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
sudo cp -f ~/hosts.new $FILE
